language: cpp

dist: xenial

compiler:
- gcc

os:
- linux

before_install:
# - sudo apt-cache search mysql
- sudo apt-get install libjemalloc-dev libjemalloc1 libjemalloc1-dbg libjsoncpp-dev libjson0 libjson0-dev libboost-dev libmysqlcppconn-dev libmysql++-dev

script:
- g++ src/game_server/main.cpp -Iexternal_library/jemalloc/include -Iexternal_library/jsoncpp/include -Iexternal_library/cpp_redis/tacopie/includes -Iexternal_library/cpp_redis/includes -Isrc/dutil -Isrc/dnetwork -std=c++11 -o DServer
- ./DServer